export const UI = {
    new: "New",
    clearData: "Clear all data and start a new session",
    edit: "Edit",
    preview: "Preview",
    download: "Download PDF",
    downloaded: "Downloaded",
    unlock: "Download PDF (300 FCFA)",
    loadSample: "Load Sample",
    resume: "Resume",
    cv: "CV",
    coverLetter: "Cover Letter",
    cvDetails: "CV Details",
    resumeDetails: "Resume Details",
    letterDetails: "Letter Details",
    craftLetter: "Craft a persuasive letter.",
    buildProfile: "Build your professional profile.",
    matchingStyle: "Matching Style",
    accentColor: "Accent Color",
    targetRole: "Target Job Role",
    recipientDetails: "Recipient Details",
    jobContext: "Job Context",
    personalInfo: "Personal Information",
    workExperience: "Work Experience",
    internships: "Internships",
    volunteering: "Volunteering",
    education: "Education",
    projects: "Projects",
    projectsResearch: "Projects / Research",
    skillsExtra: "Skills & Extra",
    generate: "Generate",
    generating: "Generating...",
    polishing: "Polishing with AI...",
    success: "Success!",
    addJob: "Add Job",
    addInternship: "Add Internship",
    addVolunteering: "Add Volunteering",
    addSchool: "Add School",
    addProject: "Add Project",
    addEntry: "Add Entry",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    linkedin: "LinkedIn",
    website: "Website",
    company: "Company",
    role: "Role",
    description: "Description",
    school: "School",
    degree: "Degree",
    skills: "Skills",
    skillsPlaceholder: "List your skills...",
    addExperience: "Add Experience",
    addEducation: "Add Education",
    certifications: "Certifications"
};

export const ROLES = [
    "Software Engineer",
    "Data Entry Specialist",
    "Project Manager",
    "Marketing Specialist",
    "Sales Representative",
    "Customer Support Agent",
    "Graphic Designer",
    "Accountant",
    "Human Resources Manager",
    "Nurse / Healthcare",
    "Teacher / Educator",
    "Business Analyst",
    "Research Scientist",
    "Academic Professor",
    "Senior Executive",
    "Student / Intern",
    "Other"
];

export const COLORS = [
    { name: "Deep Navy", hex: "#1a2332", class: "bg-slate-900" },
    { name: "Ocean Teal", hex: "#4a9b8e", class: "bg-teal-700" },
    { name: "Forest Green", hex: "#166534", class: "bg-green-800" },
    { name: "Warm Coral", hex: "#ff6b6b", class: "bg-red-500" },
    { name: "Royal Blue", hex: "#2563eb", class: "bg-blue-600" },
    { name: "Charcoal", hex: "#374151", class: "bg-gray-700" },
    { name: "Burgundy", hex: "#7f1d1d", class: "bg-red-900" },
];

export const TEMPLATES = {
  // Resume Templates
  'modern': { name: 'Modern', desc: 'Contemporary professional design' },
  'classic': { name: 'Classic', desc: 'Traditional business format' },
  'sidebar': { name: 'Sidebar', desc: 'Two-column with photo' },
  'minimalist': { name: 'Minimalist', desc: 'Clean and simple' },
  'resume-ats': { name: 'ATS Optimized', desc: 'Applicant tracking system friendly' },
  'resume-executive': { name: 'Executive', desc: 'Senior-level professional' },
  'resume-creative': { name: 'Creative', desc: 'Visual design emphasis' },
  'resume-technical': { name: 'Technical', desc: 'Engineering and IT focused' },
  'resume-entry': { name: 'Entry Level', desc: 'Graduate and career starter' },
  
  // CV Templates
  'cv-academic': { name: 'Academic CV', desc: 'University standard format' },
  'cv-executive': { name: 'Executive CV', desc: 'Leadership positions' },
  'cv-corporate': { name: 'Corporate CV', desc: 'Business professional' },
  'cv-professional': { name: 'Professional CV', desc: 'Multi-industry standard' },
  'cv-classic': { name: 'Classic CV', desc: 'Traditional comprehensive' },
  'cv-research': { name: 'Research CV', desc: 'Publications and grants focus' },
  'cv-medical': { name: 'Medical CV', desc: 'Healthcare professionals' },
  'cv-faculty': { name: 'Faculty CV', desc: 'Teaching and service emphasis' },
  'cv-scientific': { name: 'Scientific CV', desc: 'Lab and technical skills' },
  'cv-international': { name: 'International CV', desc: 'Global standard with photo' },
};

