export const UI = {
    new: "New",
    clearData: "Clear all data and start a new session",
    edit: "Edit",
    preview: "Preview",
    download: "Download PDF",
    downloaded: "Downloaded",
    unlock: "Download PDF (300 FCFA)",
    loadSample: "Load Sample",
    resume: "Resume",
    cv: "CV",
    coverLetter: "Cover Letter",
    cvDetails: "CV Details",
    resumeDetails: "Resume Details",
    letterDetails: "Letter Details",
    craftLetter: "Craft a persuasive letter.",
    buildProfile: "Build your professional profile.",
    matchingStyle: "Matching Style",
    accentColor: "Accent Color",
    targetRole: "Target Job Role",
    recipientDetails: "Recipient Details",
    jobContext: "Job Context",
    personalInfo: "Personal Information",
    workExperience: "Work Experience",
    internships: "Internships",
    volunteering: "Volunteering",
    education: "Education",
    projects: "Projects",
    projectsResearch: "Projects / Research",
    skillsExtra: "Skills & Extra",
    generate: "Generate",
    generating: "Generating...",
    polishing: "Polishing with AI...",
    success: "Success!",
    addJob: "Add Job",
    addInternship: "Add Internship",
    addVolunteering: "Add Volunteering",
    addSchool: "Add School",
    addProject: "Add Project",
    addEntry: "Add Entry",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    linkedin: "LinkedIn",
    website: "Website",
    company: "Company",
    role: "Role",
    description: "Description",
    school: "School",
    degree: "Degree",
    skills: "Skills",
    skillsPlaceholder: "List your skills...",
    addExperience: "Add Experience",
    addEducation: "Add Education",
    certifications: "Certifications"
};

export const ROLES = [
    "Software Engineer",
    "Data Entry Specialist",
    "Project Manager",
    "Marketing Specialist",
    "Sales Representative",
    "Customer Support Agent",
    "Graphic Designer",
    "Accountant",
    "Human Resources Manager",
    "Nurse / Healthcare",
    "Teacher / Educator",
    "Business Analyst",
    "Research Scientist",
    "Academic Professor",
    "Senior Executive",
    "Student / Intern",
    "Other"
];

export const COLORS = [
    { name: "Deep Navy", hex: "#1a2332", class: "bg-slate-900" },
    { name: "Ocean Teal", hex: "#4a9b8e", class: "bg-teal-700" },
    { name: "Forest Green", hex: "#166534", class: "bg-green-800" },
    { name: "Warm Coral", hex: "#ff6b6b", class: "bg-red-500" },
    { name: "Royal Blue", hex: "#2563eb", class: "bg-blue-600" },
    { name: "Charcoal", hex: "#374151", class: "bg-gray-700" },
    { name: "Burgundy", hex: "#7f1d1d", class: "bg-red-900" },
];
